api:
  insecure: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: traefik

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "murodjonfaiziev@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
