api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"  # Исправлено с "schema" на "scheme"

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "murodjonfaiziev@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
